Repository solana-foundation/developer-content, pull requests merged in 2024-10, with the labels that each got.

#461 Mobile Development: Update the docs + code of Solana Mobile Dapps with Expo
  content/courses/mobile/solana-mobile-dapps-with-expo.md
Labels: superteam-lesson-updates

#476 Update Lookup Tables (LUTs) course
  content/courses/program-optimization/lookup-tables.md
Labels: superteam-lesson-updates, superteam-winner

#510 feat: update compressed-nfts.md to use umi and bubblegum plugin
  content/courses/state-compression/compressed-nfts.md
  public/assets/courses/unboxed/solana-explorer-create-tree.png
  public/assets/courses/unboxed/solana-explorer-showing-cnft-transfer-logs.png
Labels: superteam-lesson-updates

#478 Updated Intro to solana mobile
  content/courses/mobile/intro-to-solana-mobile.md
Labels: superteam-lesson-updates

#493 Native onchain development - Updated cross program invocation lesson
  content/courses/native-onchain-development/cross-program-invocations.md
Labels: superteam-lesson-updates, superteam-winner, hacktoberfest

#349 onchain-development intro-to-anchor updated
  content/courses/onchain-development/intro-to-anchor.md
Labels: superteam-lesson-updates, superteam-winner, hacktoberfest

#485 Program Optimization - Updated Program Architecture lesson
  content/courses/program-optimization/program-architecture.md
Labels: superteam-lesson-updates, superteam-winner, hacktoberfest, hacktoberfest-accepted

#536 fix and improve close-mint course
  content/courses/token-extensions/close-mint.md
Labels: superteam-lesson-updates, superteam-winner, hacktoberfest, hacktoberfest-accepted

#440 Program security - Account data matching lesson updated
  content/courses/program-security/account-data-matching.md
Labels: superteam-lesson-updates, superteam-winner, hacktoberfest, hacktoberfest-accepted

#345 Update solana pay content
  content/courses/solana-pay/solana-pay.md
Labels: superteam-lesson-updates, superteam-winner, hacktoberfest, hacktoberfest-accepted

#470 Generalized state compression
  content/courses/state-compression/generalized-state-compression.md
  package.json
  yarn.lock
Labels: superteam-lesson-updates, superteam-winner, hacktoberfest, hacktoberfest-accepted

#475 Added argument checks - for better error display.
  content/courses/onchain-development/anchor-pdas.md
Labels: superteam-lesson-updates
